"""Constants for the Accurate Solar Forecast integration."""

DOMAIN = "accurate_solar_forecast"

# Configuration constants
CONF_BRAND = "brand"
CONF_VOC = "voc"
CONF_ISC = "isc"
CONF_VMP = "vmp"
CONF_IMP = "imp"
CONF_STRING_NAME = "string_name"
CONF_TEMP_SENSOR = "temperature_sensor"
CONF_WIND_SENSOR = "wind_sensor"
CONF_PANEL_MODEL = "panel_model"
CONF_NUM_PANELS = "num_panels"
CONF_NUM_STRINGS = "num_strings"
CONF_TILT = "tilt"
CONF_AZIMUTH = "azimuth"
CONF_REF_SENSOR = "irradiance_sensor"
CONF_REF_ORIENTATION = "ref_orientation"
CONF_REF_TILT = "ref_tilt"
